### ISSUE TITLE
最低限の ci を用意する

### ISSUE THREAD

**Issue by lirlia** [recursion-team-v/bomb#4]

**Comment by hiroto0222** [comment]
正直今回の monorepo の github actions での eslint、prettier の導入にちょっと苦戦しています。
今の所以下を試しています

```yml
# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: install frontend modules
        run: npm run install:frontend

      - name: lint frontend
        run: npm run lint:frontend

      - name: format frontend
        run: npm run format:frontend

      - name: check modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: automated changes"

  backend-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
  ...
```

```
# package.json (root)

{
  ...
  "scripts": {
    "install:frontend": "cd frontend && npm install",
    "lint:frontend": "cd frontend && npm run lintfix",
    "format:frontend": "cd frontend && npm run format",
    "install:backend": "cd backend && npm install",
    ...
  },
  ...
}
```
